### ISSUE TITLE
Google Calnedar: Hard to see title/date/time/description in popup of schedule

### ISSUE THREAD

**Issue by Y-intk** [EvHaus/google-redesigned#13] opened 2023-01-10 03:18 UTC
Hi, your Material Dark Google Calendar is so cool and elegant in visual effect, it's my favorite theme, but unfortunately the text color of title/date/time/description in popup of schedule is similar to its background so it's hardly visible.
Also, calendar titles shown on the left are also invisible. 
![image](https://user-images.githubusercontent.com/121005980/211453762-52f033da-93d7-40cc-b098-cbbca2743f1c.png)

This theme will be perfect for me if these issue are resolved.
How can I fix it?
Thank you for your consideration in advance. Regards,

**Comment by EvHaus** [comment] 2023-01-10 04:44
Thanks! I'm unable to reproduce this issue at the moment. It's likely Google is making changes to their app right now. I will fix this as soon as possible.

**Comment by EvHaus** [comment] 2023-01-27 03:15
Should be fixed in latest 20230126.0.0 version.

**Closed by EvHaus** 2023-01-27 03:15 UTC
